# TD2 block 개수 실험 - 31.72M
growth_rate: [42, 42, 42, 42]
num_layers: [6, 12, 24, 16]
num_td2_blocks: [3, 3, 3, 3]
out_block: [6, 12, 24, 16]
block_comp: [0.5, 0.5, 0.5, 1]
trans_comp_factor: [2, 2, 2, 1]
kernel_size: 3
is_cbr: True
dropout_p: 0.2 