# TD2 block 개수 실험 - 31.58M
growth_rate: [52, 52, 52, 52]
num_layers: [6, 12, 24, 16]
num_td2_blocks: [2, 2, 2, 2]
out_block: [6, 12, 24, 16]
block_comp: [0.5, 0.5, 0.5, 1]
trans_comp_factor: [2, 2, 2, 1]
kernel_size: 3
is_cbr: True
dropout_p: 0.2 