growth_rate: [32, 32, 32, 32]
num_layers: [6, 6, 6, 6]
num_td2_blocks: [4, 4, 4, 4]
out_block: [6, 6, 6, 6]
block_comp: [0.5, 0.5, 0.5, 0.5]
trans_comp_factor: [2, 2, 2, 1]
kernel_size: 3
is_cbr: True
dropout_p : 0.2

